name: amwang
description: Blogging about stuffs
meta_description: "amwang's Blog"

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

    highlighter: pygments
    logo: false
    paginate: 20
    baseurl: /
    domain_name: 'http://amwang25.github.io/'
    google_analytics: ''

        # Details for the RSS feed generator
        # url:            '/rss.xml'
        # author:         'amwang'
